#!/usr/bin/env python3
"""Install or uninstall Looop command shims without external dependencies."""

from __future__ import annotations

import os
import shutil
import stat
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "looop"
SHIM_MARKER = "# generated by the Looop installer"


def prefix() -> Path:
    return Path(os.environ.get("PREFIX", Path.home() / ".local")).expanduser()


def app_dir() -> Path:
    return prefix() / "share" / PACKAGE


def bin_dir() -> Path:
    override = os.environ.get("LOOOP_BIN_DIR") or os.environ.get("BIN_DIR")
    if override:
        return Path(override).expanduser()

    preferred = prefix() / "bin"
    if _command_would_resolve_from(preferred, "lp"):
        return preferred

    for candidate in (Path("/opt/homebrew/bin"), Path("/usr/local/bin")):
        if _command_would_resolve_from(candidate, "lp"):
            return candidate
    return preferred


def path_entries() -> list[Path]:
    return [Path(entry).expanduser() for entry in os.environ.get("PATH", "").split(os.pathsep) if entry]


def _first_executable_index(command: str) -> int | None:
    for index, directory in enumerate(path_entries()):
        candidate = directory / command
        if candidate.exists() and os.access(candidate, os.X_OK):
            return index
    return None


def _path_index(directory: Path) -> int | None:
    resolved = directory.expanduser()
    for index, entry in enumerate(path_entries()):
        if entry == resolved:
            return index
    return None


def _command_would_resolve_from(directory: Path, command: str) -> bool:
    candidate_index = _path_index(directory)
    if candidate_index is None:
        return False
    existing_index = _first_executable_index(command)
    return existing_index is None or candidate_index <= existing_index


def write_shim(command: str, python_executable: str) -> None:
    target = bin_dir() / command
    if target.exists() and not is_our_shim(target):
        raise RuntimeError(f"Refusing to overwrite existing non-Looop command: {target}")
    shim = f"""#!{python_executable}
{SHIM_MARKER}
import sys

sys.path.insert(0, {str(app_dir())!r})

from looop.cli import main

raise SystemExit(main())
"""
    target.write_text(shim, encoding="utf-8")
    mode = target.stat().st_mode
    target.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install() -> int:
    target_app = app_dir()
    target_bin = bin_dir()
    target_bin.mkdir(parents=True, exist_ok=True)
    target_app.parent.mkdir(parents=True, exist_ok=True)

    if target_app.exists():
        shutil.rmtree(target_app)
    target_app.mkdir(parents=True)

    shutil.copytree(ROOT / PACKAGE, target_app / PACKAGE)
    for filename in ("pyproject.toml", "README.md", "LICENSE"):
        shutil.copy2(ROOT / filename, target_app / filename)

    write_shim("looop", sys.executable)
    write_shim("lp", sys.executable)

    print(f"Installed looop package files to {target_app}")
    print(f"Installed commands to {target_bin}: looop, lp")

    if target_bin not in set(path_entries()):
        print(f"Warning: {target_bin} is not in PATH.", file=sys.stderr)
    return 0


def is_our_shim(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return SHIM_MARKER in text or ("from looop.cli import main" in text and "sys.path.insert" in text)


def candidate_uninstall_bins() -> list[Path]:
    candidates = [bin_dir(), prefix() / "bin", Path("/opt/homebrew/bin"), Path("/usr/local/bin")]
    seen: set[Path] = set()
    unique: list[Path] = []
    for candidate in candidates:
        expanded = candidate.expanduser()
        if expanded not in seen:
            unique.append(expanded)
            seen.add(expanded)
    return unique


def uninstall() -> int:
    removed = False
    for directory in candidate_uninstall_bins():
        for command in ("looop", "lp"):
            target = directory / command
            if (target.exists() or target.is_symlink()) and is_our_shim(target):
                target.unlink()
                print(f"Removed {target}")
                removed = True
    if app_dir().exists():
        shutil.rmtree(app_dir())
        print(f"Removed {app_dir()}")
        removed = True
    if not removed:
        print("No Looop installation found.")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    try:
        if args == ["install"]:
            return install()
        if args == ["uninstall"]:
            return uninstall()
        print("usage: install.py [install|uninstall]", file=sys.stderr)
        return 2
    except (OSError, RuntimeError) as exc:
        print(f"looop installer: error: {exc}", file=sys.stderr)
        print(
            "Set LOOOP_BIN_DIR=/path/to/bin to choose a different command directory.",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
